pipeline {

    agent any

    stages {

        stage("Recover artifacts from build pipeline") {
            steps {
                copyArtifacts(
                    projectName: "front-vuelos-build",
                    selector: upstream(),
                    filter: "build/**"
                )
            }
        }

        stage('Copy nginx config to VM') {
             steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'hiking',
                            transfers: [
                                sshTransfer(
                                    sourceFiles: 'nginx/**',
                                    removePrefix: 'nginx', 
                                    remoteDirectory: 'nginx_config/',
                                    execCommand: 'home/hikingcarrot7/utils/copy_nginx_config'
                                )
                            ]
                        )
                    ]
                )
            }
        }



    }
}
