pipeline {

    agent any

    stages {

        stage("Recover artifacts from build pipeline") {
            steps {
                copyArtifacts(
                    projectName: "front-vuelos-build",
                    selector: upstream(),
                    filter: "build/**"
                )
            }
        }

        stage('Copy nginx config') {
             steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'server',
                            transfers: [
                                sshTransfer(
                                    sourceFiles: 'nginx/**',
                                    removePrefix: 'nginx',
                                    remoteDirectory: 'nginx_config',
                                    execCommand: 'cp nginx_config/* /etc/nginx/',
                                )
                            ]
                        )
                    ]
                )
            }
        }

        stage('Copy build proyect to VM') {
             steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'server',
                            transfers: [
                                sshTransfer(
                                    sourceFiles: 'build/**',
                                    removePrefix: 'build',
                                    remoteDirectory: 'vuelos',
                                    execCommand: 'rm -r /usr/share/nginx/html/*; mv vuelos/* /usr/share/nginx/html',
                                )
                            ]
                        )
                    ]
                )
            }
        }


    }
}
